### ISSUE TITLE
`RDGamma` &  `RDGammaSync` - 속담의 형태소로부터 속담의 임베딩 계산 &  예시에 어텐션 적용 &  말그대로의 의미 - 비유적인 의미 동기화

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#115]

**Comment by eubinecto** [comment]
## GPU에서 학습 진행시 에러 발생..

```
Traceback (most recent call last):
  File "/workspace/wisdomify/main_train.py", line 73, in <module>
    main()
  File "/workspace/wisdomify/main_train.py", line 56, in main
    trainer.fit(model=flow.rd_flow.rd, datamodule=flow.datamodule)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 141, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_idx + 1)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 199, in __iter__
    self.prefetching(self.prefetch_batches)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 258, in prefetching
    self._fetch_next_batch()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/supporters.py", line 550, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/trainer/supporters.py", line 562, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 92, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/wisdomifyenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/wisdomify/wisdomify/datamodules.py", line 36, in __getitem__
    return self.X[idx], self.y[idx]
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by eubinecto** [comment]
## 원인이 무엇일까?

일단... 에러가 나는 곳이.... 
```
  File "/workspace/wisdomify/wisdomify/datamodules.py", line 36, in __getitem__
    return self.X[idx], self.y[idx]
```
이 부분임에 주목하자.  Dataset에서 배치에 해당하는 것을 가져올 때, 문제가 발생한다
