### ISSUE TITLE
`RDBetaWithAttention` 구현 & 테스트

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#95]
## What?
어텐션을 사용하여   H_eg를 계산하기.

## Why?
....(fill this in later)...

## How?
- 가급적이면 새로운 신경망 레이어는 추가를 하지 않는 방향.
- 그리고 신경망의 추가가 반드시 필요한 경우 -> 반드시 적절한 이유를 설명할 것.
- https://github.com/wisdomify/wisdomify/pull/88#discussion_r738336342
  - `H_wisdom`을 구할 때, 어텐션을 사용하는 방법?

## To-do's
- [x] 일단,  68번 마무리가 되는걸 기다리기!
- [ ] `RDBeta`랑 비교해보기.

**Comment by Yuuraa** [comment]
### RDBetaAttention

기존 RDBeta는 H_wisdom으로부터 wisdom 부분 토큰들의 hidden state를 pooling 때, 기존에는 K개의 wisdom 토큰에서 나온 hidden state 값들을 평균냈다. Hidden state를 pooling하는 이유는 이후에 올 linear layer의 파라미터 수를 줄이기 위해 필수적인데, 전체 K개를 평균을 취하게 됐을 때 정보의 손실이 일어날 수도 있다는 단점이 있다.

따라서 RDBetaAttention은 문장의 전체적인 의미를 담고 있는 부분인 H_cls와의 attention을 계산하고, 해당 attention 점수를 활용하여 H_wisdom 토큰들을 pooling한다. Attention layer를 사용하는 방식은 아니고, dot product를 취해 유사도를 기반으로 점수를 구했다. 레이어를 더 추가하는 것을 막기 위해 dot product를 취하는 부분만을 점수를 구하는 부분으로 고려했다.

🤔❓ ```의문점```: 이렇게 유사도를 구했을 때 얻을 수 있는 장점이 있거나 취약점이 생긴다면 어떻게 확인할 수 있을까? 사실 입력되는 wisdom 토큰은 전부 [MASK] 형태로 들어가는데, 이 각각의 토큰에서 나온 값들이 [CLS] 토큰과의 점수를 계산하면, 아마 대부분 함께 입력으로 들어간 정의 문장에서 나온 결과를 사용하지 않을까?

**models.py**
추가된 부분: H_wisdom 토큰을 합할 때 H_cls 토큰과의 attention을 기반으로 하자
```python
        # Apply attention: H_wisdom with H_wisdom to encode more relationship
        H_wisdom = self.H_k(H_all)  # (N, K, H)
        Attn_wisdom = torch.einsum('nh,nqh -> nq', H_cls, H_wisdom) # (N, K, H) -> (N, K)
        H_wisdom = torch.einsum('nq,nqh -> nh', Attn_wisdom, H_wisdom)  # (N, K, H) * 
```

**Comment by Yuuraa** [comment]
### Warning
일단 CPU에서 모델을 실행했을 때, 이런 warning이 뜨는 것을 확인했다. 왜 뜨는 것일지 확인 필요!!

```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1566: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  rank_zero_warn(
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py:341: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(

  | Name       | Type            | Params
-----------------------------------------------
0 | bert_mlm   | BertForMaskedLM | 108 M 
1 | rd_metric  | RDMetric        | 0     
2 | cls_fc     | FCLayer         | 196 K 
3 | wisdom_fc  | FCLayer         | 196 K 
4 | example_fc | FCLayer         | 196 K 
5 | final_fc   | FCLayer         | 590 K 
-----------------------------------------------
110 M     Trainable params
0         Non-trainable params
110 M     Total params
440.556   Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:394: UserWarning: The number of training samples (2) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.43s/it, loss=15.7, v_num=18yo/home/yura/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: The ``compute`` method of metric RDMetric was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
home/yura/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: The ``compute`` method of metric RDMetric was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
/home/yura/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/yura/.local/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/yura/.local/lib/python3.8/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/yura/.local/lib/python3.8/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/home/yura/.local/lib/python3.8/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by Yuuraa** [comment]
### Inference 결과
wisom2def v0(a)으로 학습 및 테스트
![image](https://user-images.githubusercontent.com/48202492/141118285-c05b69ac-71ad-4b65-a51a-4812214ae22c.png)

**Comment by Yuuraa** [comment]
### GPU 사용시 발생하는 에러

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py:341: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Testing: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yura/Smilegate_AI/Sesame_Street/wisdomify/wisdomify/main/eval.py", line 40, in <module>
    main()
  File "/home/yura/Smilegate_AI/Sesame_Street/wisdomify/wisdomify/main/eval.py", line 36, in main
    trainer.test(model=exp.rd, datamodule=exp.datamodule, verbose=True)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 904, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 947, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1268, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating
    self._results = trainer.run_stage()
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in run_stage
    return self._run_evaluate()
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1327, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 87, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 199, in __iter__
    self.prefetching(self.prefetch_batches)
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 258, in prefetching
    self._fetch_next_batch()
  File "/home/yura/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/yura/.local/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yura/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yura/Smilegate_AI/Sesame_Street/wisdomify/wisdomify/datamodules.py", line 36, in __getitem__
    return self.X[idx], self.y[idx]
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
